import { expect, test, type APIRequestContext } from "@playwright/test";
import {prisma} from '../../src/lib/database';

const account = (email:string,name="보호자") => ({email,password:"Password123!",name,ageConfirmed:true,terms:true,privacy:true});
async function signup(request:APIRequestContext,email:string,name='보호자'){const response=await request.post('/api/auth/signup',{data:account(email,name)});expect(response.status()).toBe(201);const data=await response.json();expect((await request.post('/api/auth/verify-email',{data:{code:data.testCode}})).status()).toBe(200);return response;}

test("필수 E2E 17개 사용자 시나리오", async ({page,browser})=>{
  const email=`owner-${Date.now()}@test.local`; const post=(path:string,data:unknown)=>page.request.post(path,{data});
  let caseId=""; let familyEmail="";
  await test.step("1 가입·개별 동의·민감정보 동의",async()=>{expect((await post('/api/auth/signup',{...account(email),terms:false})).status()).toBe(400);await signup(page.request,email);const r=await post('/api/cases',{patientAlias:'우리 엄마',relationship:'자녀',authority:'CAREGIVER',sensitiveConsent:true});expect(r.status()).toBe(201);caseId=(await r.json()).case.id});
  await test.step("2 기기 OCR 텍스트 저장",async()=>{const r=await post(`/api/cases/${caseId}/documents/ocr`,{fileName:'입원 안내.jpg',text:'2026년 8월 12일 오전 9시 본관 2층',confidence:93});expect(r.status()).toBe(201);const a=(await r.json()).analysis;expect(a).toMatchObject({fileName:'입원 안내.jpg',status:'CONFIRMED',originalAvailable:false});const overview=await (await page.request.get(`/api/cases/${caseId}/overview`)).json();expect(overview.documents.find((item:{id:string})=>item.id===a.id).fields.ocrText).toContain('본관 2층')});
  await test.step("3 가족 초대·수락·허용 케이스",async()=>{familyEmail=`family-${Date.now()}@test.local`;const r=await post(`/api/cases/${caseId}/invitations`,{email:familyEmail,role:'VIEWER',expiresInHours:48});const invitation=(await r.json()).invitation;const c=await browser.newContext();const p=await c.newPage();await signup(p.request,familyEmail,'가족');expect((await p.request.post('/api/invitations/accept',{data:{token:invitation.token}})).status()).toBe(200);expect((await (await p.request.get('/api/cases')).json()).items).toHaveLength(1);await c.close()});
  await test.step("4 돌봄 기록·교대 브리핑·가족 알림",async()=>{expect((await post('/api/care-logs',{meal:'1/2',pain:3})).status()).toBe(201);expect((await post('/api/handoffs',{summary:'통증 3, 약 확인'})).status()).toBe(201);const c=await browser.newContext();const p=await c.newPage();await p.request.post('/api/auth/login',{data:{email:familyEmail,password:'Password123!'}});const familyOverview=await (await p.request.get(`/api/cases/${caseId}/overview`)).json();expect(familyOverview.notifications.map((item:{category:string})=>item.category)).toEqual(expect.arrayContaining(['care-logs','handoffs']));await c.close()});
  await test.step("5 회진 질문·답변",async()=>{expect((await post('/api/questions',{question:'퇴원일은?',answer:'상태 확인 후'})).status()).toBe(201)});
  await test.step("6 비용·분담",async()=>{expect((await post('/api/expenses',{title:'용품',amount:24000,split:[12000,12000]})).status()).toBe(201)});
  await test.step("7 퇴원 체크리스트·PDF",async()=>{expect((await post('/api/discharge/items',{title:'확인서',completed:true})).status()).toBe(201);const pdf=await page.request.get('/api/discharge/pdf');expect(pdf.headers()['content-type']).toContain('pdf');const bytes=Buffer.from(await pdf.body());expect(bytes.subarray(0,4).toString()).toBe('%PDF');expect(bytes.length).toBeGreaterThan(5_000)});
  await test.step("8 OCR 횟수 제한 없음·결제 차단",async()=>{const c=await browser.newContext();const p=await c.newPage();const freeUser=`free-${Date.now()}@test.local`;await signup(p.request,freeUser);const cr=await p.request.post('/api/cases',{data:{patientAlias:'무료검사',relationship:'자녀',authority:'CAREGIVER',sensitiveConsent:true}});const cid=(await cr.json()).case.id;for(let i=0;i<5;i++)expect((await p.request.post(`/api/cases/${cid}/documents/ocr`,{data:{fileName:`안내-${i}.jpg`,text:`무료 OCR 텍스트 ${i}`,confidence:90}})).status()).toBe(201);const checkout=await p.request.post('/api/payments/checkout',{data:{plan:'ADMISSION_PASS',testOutcome:'success'}});expect(checkout.status()).toBe(410);expect((await checkout.json()).error.code).toBe('SERVICE_IS_FREE');await c.close()});
  await test.step("9 무권한 직접 접근 차단",async()=>{const c=await browser.newContext();const p=await c.newPage();await signup(p.request,`x-${Date.now()}@test.local`,'타인');expect((await p.request.get(`/api/cases/${caseId}`)).status()).toBe(404);await c.close()});
  await test.step("10 취소·만료 초대 재사용 차단",async()=>{for(const expired of [false,true]){const target=`invite-${expired}-${Date.now()}@test.local`;const r=await post(`/api/cases/${caseId}/invitations`,{email:target,role:'VIEWER',expiresInHours:1});const invitation=(await r.json()).invitation;if(expired)await prisma.invitation.update({where:{id:invitation.id},data:{expiresAt:new Date(Date.now()-1000)}});else expect((await page.request.delete(`/api/invitations/${invitation.id}`)).status()).toBe(200);const c=await browser.newContext();const p=await c.newPage();await signup(p.request,target,'초대검사');expect((await p.request.post('/api/invitations/accept',{data:{token:invitation.token}})).status()).toBe(410);await c.close()}});
  await test.step("11 동의 철회 즉시 가족 공유 중단",async()=>{expect((await post('/api/agreements',{type:'sensitive',accepted:false,version:'1.0'})).status()).toBe(201);const c=await browser.newContext();const p=await c.newPage();await p.request.post('/api/auth/login',{data:{email:familyEmail,password:'Password123!'}});expect((await p.request.get(`/api/cases/${caseId}`)).status()).toBe(404);await c.close();expect((await post('/api/privacy-requests',{type:'DELETION',detail:'민감정보 삭제'})).status()).toBe(201)});
  await test.step("12 미사용 AI·결제 기능 차단",async()=>{expect((await post(`/api/cases/${caseId}/documents/analyze`,{fileName:'guide.pdf',fixture:'admission'})).status()).toBe(410);expect((await post('/api/payments/checkout',{plan:'FAMILY_MONTHLY',testOutcome:'success'})).status()).toBe(410)});
  await test.step("13 채널별 마케팅 동의 철회",async()=>{expect((await page.request.patch('/api/preferences',{data:{channel:'marketing_email',enabled:true}})).status()).toBe(200);expect((await page.request.patch('/api/preferences',{data:{channel:'marketing_email',enabled:false}})).status()).toBe(200)});
  await test.step("14 CMS 게시·버전·공개",async()=>{const c=await browser.newContext();const p=await c.newPage();await p.request.post('/api/auth/login',{data:{email:'admin@guardian.local',password:'admin1234'}});expect((await p.request.post('/api/admin/legal',{data:{slug:`privacy-${Date.now()}`,title:'처리방침 개정',version:'2.0',body:'변경 이력과 시행일을 포함한 처리방침 초안입니다.',published:true}})).status()).toBe(201);expect((await p.request.post('/api/admin/notices',{data:{title:'서비스 공지',body:'정기 점검 안내',published:true}})).status()).toBe(201);await c.close()});
  await test.step("15 권리요청 관리자 처리",async()=>{const r=await post('/api/privacy-requests',{type:'CORRECTION',detail:'표시 이름 정정'});const rid=(await r.json()).request.id;const c=await browser.newContext();const p=await c.newPage();await p.request.post('/api/auth/login',{data:{email:'admin@guardian.local',password:'admin1234'}});expect((await p.request.patch(`/api/admin/privacy-requests/${rid}`,{data:{status:'COMPLETED',response:'정정 완료'}})).status()).toBe(200);await c.close()});
  await test.step("16 무료 이용 고지",async()=>{await page.goto('/payment');await expect(page.locator('body')).toContainText(/무료 이용|0원|모든 기능을 무료/)});
  await test.step("17 탈퇴 후 모든 세션·공유 차단",async()=>{expect((await post('/api/privacy/delete',{})).status()).toBe(201);expect((await page.request.get('/api/cases')).status()).toBe(401);expect((await page.request.post('/api/auth/login',{data:{email,password:'Password123!'}})).status()).toBe(401)});
});

test("모바일 화면과 오프라인 앱 셸",async({page,context})=>{await page.setViewportSize({width:360,height:800});for(const path of ['/','/signup','/login','/dashboard','/documents','/family','/payment','/supplies','/legal']){await page.goto(path,{waitUntil:'domcontentloaded'});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=document.documentElement.clientWidth)).toBeTruthy();await expect(page.locator('body')).not.toContainText(/TODO|준비 중|Coming soon|가짜 버튼/i)}await page.goto('/');const registered=await page.evaluate(async()=>{if(!('serviceWorker' in navigator))return false;await navigator.serviceWorker.register('/sw.js');const ready=await Promise.race([navigator.serviceWorker.ready,new Promise<null>(resolve=>setTimeout(()=>resolve(null),5000))]);return Boolean(ready)});expect(registered).toBeTruthy();await context.setOffline(true);await page.reload({waitUntil:'domcontentloaded'});await expect(page.getByRole('heading',{name:'가족 돌봄을 한곳에서, 놓치지 않게 기록하세요.'})).toBeVisible();await context.setOffline(false)});
