'use client';
import {useState} from 'react';
import {AuthFrame} from '@/components/AuthVisual';
import {ActionForm} from '@/components/ActionForm';

export default function Signup(){
  const [required,setRequired]=useState([false,false,false]);
  const [verification,setVerification]=useState<{code?:string}|null>(null);
  if(verification)return <AuthFrame><span className="eyebrow">2 / 3 이메일 확인</span><h1>인증번호를 확인해 주세요</h1><p className="sub">이메일로 보낸 6자리 번호를 입력하면 계정 확인이 끝납니다.</p>{verification.code&&<div className="notice">개발용 이메일 인증번호: <b>{verification.code}</b></div>}<ActionForm endpoint="/api/auth/verify-email" success="이메일 인증을 완료했습니다" redirect="/case/new" submitLabel="인증 완료"><div className="field"><label htmlFor="verification-code">6자리 인증번호</label><input id="verification-code" name="code" inputMode="numeric" pattern="[0-9]{6}" maxLength={6} defaultValue={verification.code} required autoComplete="one-time-code"/></div></ActionForm></AuthFrame>;
  return <AuthFrame><span className="eyebrow">1 / 3 계정 만들기</span><h1>반가워요</h1><p className="sub">필수 동의와 선택 동의를 구분해 직접 선택해 주세요.</p><ActionForm endpoint="/api/auth/register" success="가입 정보를 저장했습니다" submitLabel="가입하고 이메일 확인" onSuccess={data=>{const result=data as {testCode?:string};setVerification({code:result.testCode});}}><div className="field"><label htmlFor="signup-email">이메일</label><input id="signup-email" name="email" type="email" required placeholder="name@example.com" autoComplete="email"/></div><div className="field"><label htmlFor="signup-password">비밀번호</label><input id="signup-password" name="password" type="password" minLength={8} required placeholder="8자 이상" autoComplete="new-password"/></div><div className="field"><label htmlFor="signup-name">표시 이름</label><input id="signup-name" name="name" required placeholder="예: 김보호"/></div>{['[필수] 이용약관 동의','[필수] 개인정보 수집·이용 동의','[필수] 만 14세 이상입니다'].map((label,index)=><label className="check" key={label}><input name={`required${index}`} type="checkbox" required checked={required[index]} onChange={event=>setRequired(value=>value.map((checked,current)=>current===index?event.target.checked:checked))}/><span>{label}<small>전문과 수집 목적, 보유 기간 보기</small></span></label>)}<label className="check"><input name="marketing" type="checkbox"/><span>[선택] 유용한 소식 받기<small>설정에서 언제든 철회할 수 있습니다</small></span></label><div style={{height:16}}/></ActionForm></AuthFrame>;
}
